title: Sales Orders Analysis
author: Anita
logo: ""

execute:
  execute_notebooks: force

html:
  use_issues_button: off
  use_repository_button: true

repository:
  url: https://github.com/anitaexx/SalesOrdersAnalysis
  path_to_book: book
  branch: main
